/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.os890.cdi.uml.dynamic.flow.renderer.runtime;

import java.lang.reflect.Method;

/**
 * Maps a (possibly proxied) runtime-class back to the bean-class an application-developer wrote.
 * <p>
 * Both Weld and OpenWebBeans put generated classes into the call-chain - client-proxies for
 * normal-scoped beans and interceptor-subclasses for intercepted beans. Their names
 * ({@code Foo$Proxy$_$$_WeldSubclass}, {@code Foo$$OwbNormalScopeProxy}, ...) must never show up
 * in a diagram.
 * <p>
 * Detection is deliberately name-based. The addon is compiled against the CDI API/SPI only, so it
 * cannot reference {@code WeldConstruct} or {@code OwbNormalScopeProxy} - but it can recognize
 * that a class implements an interface from one of those packages.
 */
public final class ProxyNames {

    private static final String[] GENERATED_NAME_MARKERS = {
            "$$",             //Weld subclasses/proxies and every OpenWebBeans proxy
            "$Proxy",         //Weld client-proxies and java.lang.reflect proxies
            "_Subclass",      //interceptor-subclasses
            "_ClientProxy",
            "$HibernateProxy",
            "/"               //hidden classes
    };

    private static final String[] GENERATED_INTERFACE_PACKAGES = {
            "org.jboss.weld.",
            "org.apache.webbeans."
    };

    private ProxyNames() {
    }

    /**
     * @param target the object the interceptor was invoked on - may be a container-generated subclass
     * @param method the intercepted method, used as the fallback when the target is unusable
     * @return the bean-class to show in the diagram
     */
    public static Class<?> unproxy(Object target, Method method) {
        Class<?> candidate = target != null ? target.getClass() : method.getDeclaringClass();

        while (candidate != null && candidate != Object.class && isGenerated(candidate)) {
            candidate = candidate.getSuperclass();
        }

        if (candidate == null || candidate == Object.class) {
            //e.g. a proxy which only implements interfaces - the declaring class is still clean
            return method.getDeclaringClass();
        }
        return candidate;
    }

    /**
     * @return {@code true} when the class was generated by a CDI implementation rather than written
     * by an application-developer
     */
    public static boolean isGenerated(Class<?> type) {
        if (type.isSynthetic() || type.isHidden()) {
            return true;
        }
        //covers the generated $ProxyN class as well as java.lang.reflect.Proxy it extends
        if (java.lang.reflect.Proxy.class.isAssignableFrom(type)) {
            return true;
        }

        String name = type.getName();
        for (String marker : GENERATED_NAME_MARKERS) {
            if (name.contains(marker)) {
                return true;
            }
        }

        for (Class<?> implementedInterface : type.getInterfaces()) {
            String interfaceName = implementedInterface.getName();
            for (String generatedPackage : GENERATED_INTERFACE_PACKAGES) {
                if (interfaceName.startsWith(generatedPackage)) {
                    return true;
                }
            }
        }
        return false;
    }
}
